DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = observer-main

TARGETDIRS += ../../platform 

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki


include $(CONTIKI)/Makefile.include
