DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = observer-main

TARGETDIRS += ../../platform 

PROJECT_SOURCEFILES += si1147.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki


include $(CONTIKI)/Makefile.include
